name: Deploy RADocs

on: workflow_dispatch

jobs:
  Deploy-Documentation-Site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install git+https://github.com/cmitu/mkdocs-altlink-plugin
      - run: bash generate-docs.sh

